In [1]:
import numpy as np
# scipy.special for the sigmoid function expit()
import scipy.special as sigmoid

In [18]:
# neural network class definition
class neuralNetwork:
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc 
        self.wih = np.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))

        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: sigmoid.expit(x)
        
        pass
    
    # predict
    def predict(self, inputs_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
        pass
    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), 
                                        np.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), 
                                        np.transpose(inputs))
        
        pass

In [19]:
#number of rows
train_rows = 10
test_rows = 2

# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 5
output_nodes = 1

# learning rate is 0.3
learning_rate = 0.3

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

In [20]:
np.random.seed(123)
train_data = np.random.rand(train_rows, input_nodes)
train_data

array([[ 0.69646919,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176],
       [ 0.53155137,  0.53182759,  0.63440096],
       [ 0.84943179,  0.72445532,  0.61102351],
       [ 0.72244338,  0.32295891,  0.36178866],
       [ 0.22826323,  0.29371405,  0.63097612]])

In [21]:
np.random.seed(100)
targets = np.random.rand(train_rows,1)
targets

array([[ 0.54340494],
       [ 0.27836939],
       [ 0.42451759],
       [ 0.84477613],
       [ 0.00471886],
       [ 0.12156912],
       [ 0.67074908],
       [ 0.82585276],
       [ 0.13670659],
       [ 0.57509333]])

In [22]:
n.train(train_data, targets)

In [25]:
np.random.seed(150)
test_data = np.random.rand(test_rows, input_nodes)
test_data

array([[ 0.90858394,  0.25797164,  0.87765514],
       [ 0.73896548,  0.69807652,  0.51720855]])

In [26]:
n.predict(test_data)

array([[ 0.44243221,  0.43144895]])