In [416]:
import numpy as np
# scipy.special for the sigmoid function expit()
import scipy.special as sigmoid
import pandas as pd

In [417]:
# neural network class definition
class neuralNetwork:
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc 
        self.wih = np.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))

        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: sigmoid.expit(x)
        
        pass
    
    # predict
    def predict(self, inputs_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
        pass
    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * np.dot((output_errors * final_outputs * (1.0 - final_outputs)), 
                                        np.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), 
                                        np.transpose(inputs))
        
        pass

In [418]:
#number of rows
train_rows = 10
test_rows = 2

# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 5
output_nodes = 1

# learning rate is 0.3
learning_rate = 0.3

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

In [419]:
np.random.seed(123)
train_data = np.random.rand(train_rows, input_nodes)
train_data.shape

(10, 3)

In [420]:
np.random.seed(100)
targets = np.random.rand(train_rows,1)
targets.shape

(10, 1)

In [421]:
n.train(train_data, targets)

In [422]:
np.random.seed(150)
test_data = np.random.rand(test_rows, input_nodes)
test_data

array([[ 0.90858394,  0.25797164,  0.87765514],
       [ 0.73896548,  0.69807652,  0.51720855]])

In [423]:
n.predict(test_data)

array([[ 0.44145261,  0.44400357]])

## wine

In [424]:
path = "/Users/jacoboleon/Desktop/winequality/winequality-white.csv"
df = pd.read_csv(path, delimiter=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [425]:
df.shape

(4898, 12)

In [426]:
X = df[df.columns[0:11]].values
X.shape

(4898, 11)

In [427]:
y = np.array(df[df.columns[11:]])
y.shape

(4898, 1)

In [428]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [429]:
X_train

array([[  5.6 ,   0.28,   0.4 , ...,   3.21,   0.43,  12.1 ],
       [  8.3 ,   0.41,   0.51, ...,   3.02,   0.55,  11.4 ],
       [  5.3 ,   0.31,   0.38, ...,   3.34,   0.46,  11.7 ],
       ..., 
       [  7.6 ,   0.27,   0.52, ...,   3.02,   0.53,  11.4 ],
       [  6.3 ,   0.24,   0.29, ...,   3.17,   0.38,  10.6 ],
       [  8.1 ,   0.27,   0.35, ...,   3.22,   0.63,  10.4 ]])

In [430]:
X_train.shape

(3281, 11)

In [431]:
y_train

array([[7],
       [5],
       [6],
       ..., 
       [6],
       [6],
       [8]])

In [432]:
y_train.shape

(3281, 1)

In [433]:
X_test

array([[  6.        ,   0.29      ,   0.41      , ...,   3.09      ,
          0.59      ,  10.96666667],
       [  5.4       ,   0.53      ,   0.16      , ...,   3.2       ,
          0.53      ,  13.2       ],
       [  7.1       ,   0.25      ,   0.39      , ...,   3.28      ,
          0.43      ,  12.2       ],
       ..., 
       [  6.9       ,   0.18      ,   0.38      , ...,   3.1       ,
          0.42      ,  10.5       ],
       [  7.6       ,   0.31      ,   0.24      , ...,   3.05      ,
          0.44      ,  11.8       ],
       [  6.6       ,   0.27      ,   0.29      , ...,   3.31      ,
          0.79      ,   9.8       ]])

In [434]:
X_test.shape

(1617, 11)

In [435]:
y_test

array([[7],
       [8],
       [8],
       ..., 
       [5],
       [7],
       [5]])

In [436]:
y_test.shape

(1617, 1)

In [437]:
X_train.shape[1]

11

In [691]:
# number of input, hidden and output nodes
input_nodes = X_train.shape[1]
hidden_nodes = 35
output_nodes = 1

# learning rate is 0.3
learning_rate = 0.000001

# create instance of neural network
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [692]:
n.train(X_train, y_train)

In [693]:
o = n.predict(X_test)
o = (o*10).astype('int')

In [694]:
o.max()

8

In [695]:
o.min()

6

In [696]:
o

array([[7, 7, 7, ..., 7, 7, 7]])

In [697]:
y.max()

9

In [698]:
y.min()

3

In [699]:
o = (o).T
o.shape

(1617, 1)

In [700]:
y_test.shape

(1617, 1)

In [701]:
hits = 0

for i in range(1,len(o)):
    if(o[i] == y_test[i]):
        hits+=1
        
print('performance:', round((hits/o.shape[0])*100), '%')

performance: 17 %
